[GalacticOriginal] 

NAXIS1 = 10801
NAXIS2 = 601 
CRPIX1 = 5401 
CRPIX2 = 301
CDELT1 = -0.0166666
CDELT2 =  0.0166666
CTYPE1 = 'GLON-CAR'
CTYPE2 = 'GLAT-CAR'
CRVAL1 = 90.0 
CRVAL2 = 0.0 

[GalacticEffelsberg] 

NAXIS1 = 5401
NAXIS2 = 361 
CRPIX1 = 2701 
CRPIX2 = 181
CDELT1 = -0.0333333333333
CDELT2 = 0.0333333333333
CTYPE1 = 'GLON-CAR'
CTYPE2 = 'GLAT-CAR'
CRVAL1 = 90.0 
CRVAL2 = 0.0 


[Galactic] 

NAXIS1 = 10801
NAXIS2 = 721 
CRPIX1 = 5401 
CRPIX2 = 361
CDELT1 = -0.0166666
CDELT2 =  0.0166666
CTYPE1 = 'GLON-CAR'
CTYPE2 = 'GLAT-CAR'
CRVAL1 = 90.0 
CRVAL2 = 0.0 


[LDN1111]#fg12

NAXIS1 = 601
NAXIS2 = 601 
CRPIX1 = 301 
CRPIX2 = 301
CDELT1 = -0.0166666
CDELT2 =  0.0166666
CTYPE1 = 'GLON-CAR'
CTYPE2 = 'GLAT-CAR'
CRVAL1 = 99.6
CRVAL2 = 3.7

[M31]

NAXIS1 = 601
NAXIS2 = 601 
CRPIX1 = 301 
CRPIX2 = 301
CDELT1 = -0.0166666
CDELT2 =  0.0166666
CTYPE1 = 'GLON-CAR'
CTYPE2 = 'GLAT-CAR'
CRVAL1 = 121.174329 
CRVAL2 = -21.573309

[Perseus]

NAXIS1 = 601
NAXIS2 = 601 
CRPIX1 = 301 
CRPIX2 = 301
CDELT1 = -0.0166666
CDELT2 =  0.0166666
CTYPE1 = 'GLON-CAR'
CTYPE2 = 'GLAT-CAR'
CRVAL1 = 160.014	
CRVAL2 = -18.503

[California] #fg11

NAXIS1 = 601
NAXIS2 = 601 
CRPIX1 = 301 
CRPIX2 = 301
CDELT1 = -0.0166666
CDELT2 =  0.0166666
CTYPE1 = 'GLON-CAR'
CTYPE2 = 'GLAT-CAR'
CRVAL1 = 161.0	
CRVAL2 = -10.0


[TauA]

NAXIS1 = 601
NAXIS2 = 601 
CRPIX1 = 301 
CRPIX2 = 301
CDELT1 = -0.0166666
CDELT2 =  0.0166666
CTYPE1 = 'GLON-CAR'
CTYPE2 = 'GLAT-CAR'
CRVAL1 = 184.5547 
CRVAL2 = -5.7833

