band = 0
wcs_def = "M31"
source = "fg4"
source_group = "Foreground"
offset_length = 100
feeds = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,]
map_name = "comap_fg4_071225"
tod_data_name = "level2/binned_filtered_data"
log_file_name = "/scratch/nas_comap1/sharper/student_pipeline_test/COMAP_Reduce_2024/logs/2025-12-08_11-46-30_main_run.log"
sigma_red_cutoff = 0.4
database = "/scratch/nas_comap1/sharper/student_pipeline_test/COMAP_Reduce_2024/databases/COMAP_manchester.db"
file_list = "/scratch/nas_comap1/sharper/student_pipeline_test/COMAP_Reduce_2024/modules/MapMaking/map_making_configs/file_list.txt"
output_filename = "comap_fg4_071225_band00_feed01-02-03-04-05-06-07-08-09-10-11-12-13-14-15-16-17-18-19.fits"
output_dir = "/scratch/nas_core2/sharper/COMAP/level2_data_2024/level2_maps/all_feeds"
lambda_ridge = 0.01
planck_30_path = "/scratch/nas_cbassarc/sharper/work/CBASS_PolarisedTF/ancillary_data/planck_pr3/LFI_SkyMap_030-BPassCorrected_1024_R3.00_full.fits"
calib_path = "/scratch/nas_cbassarc/sharper/work/COMAP/COMAP_Reduce_2024/notebooks/source_fitting/TauA_best_fits.npy"
